app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('homepage.urls')),
]

app/homepage/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name= 'homepage'
urlpatterns = [
    path('', views.index, name='index'),
    path('news', views.news_list, name='news_list'),
    path('news/<int:pk>', views.news_detail, name='news_detail'),
    path('contact', views.contact, name='contact'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/homepage/models.py
from django.db import models

# Create your models here.

class News(models.Model):
    title = models.CharField('タイトル', max_length=100)
    body = models.TextField('本文')
    image = models.ImageField('画像', upload_to='news_images', null=True, blank=True)
    item1 = models.CharField('項目1', max_length=100, null=True, blank=True)
    content1 = models.TextField('内容1', null=True, blank=True)
    item2 = models.CharField('項目2', max_length=100, null=True, blank=True)
    content2 = models.TextField('内容2', null=True, blank=True)
    item3 = models.CharField('項目3', max_length=100, null=True, blank=True)
    content3 = models.TextField('内容3', null=True, blank=True)
    is_published = models.BooleanField('公開フラグ', default=True)
    created = models.DateTimeField('作成日時', auto_now_add=True)

    def __str__(self):
        return self.title
    
class Contact(models.Model):

    name = models.CharField('名前', max_length=100)
    email = models.EmailField('返信用アドレス', max_length=255)
    body = models.TextField('内容')

    def __str__(self):
        return self.name

app/homepage/views.py
from typing import Any
from django.shortcuts import render

# Create your views here.

from django.views.generic import TemplateView, ListView, DetailView
from .models import News


class IndexView(TemplateView):

    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        news_list = News.objects.filter(is_published=True).order_by('-created')[:6]
        context['news_list'] = news_list
        return context

index = IndexView.as_view()

from django.views.generic import ListView
from .models import News

class NewsListView(ListView):

    template_name = 'news/list.html'
    model = News
    context_object_name = 'news_list'

news_list = NewsListView.as_view()

from django.views.generic import DetailView
from .models import News

class NewsDetailView(DetailView):

    template_name = 'news/detail.html'
    model = News
    context_object_name = 'news'

news_detail = NewsDetailView.as_view()

from django.views.generic import CreateView
from django.urls import reverse_lazy
from .models import Contact

class ContactView(CreateView):

    template_name = 'contact.html'
    model = Contact
    fields = ('name', 'email', 'body')
    success_url = reverse_lazy('homepage:index')

    def form_valid(self, form):
        contact = form.save()
        print(contact.body)
        return super().form_valid(form)

contact = ContactView.as_view()

app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-transparent nav-absolute">
        <div class="container">
            <a class="navbar-brand logo-font logo-text" href="/"><span>メイトクツールズ</span>
                <img src="{% static 'assets/img/logo_desktop.png' %}" alt="" width="auto" height="28" class="d-inline-block align-text-top">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/news">System Overview</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/contact"><i class="fa-regular fa-envelope"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    

    {% block main %}{% endblock %}


<script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

app/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

<div class="container py-4 mt-5"></div>
    <h1>お問い合わせ</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">送信</button>
    </form>
</div>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

<div class="video-background">
    <video autoplay muted loop id="bg-video">
        <source src="{% static 'assets/img/background.mp4' %}" type="video/mp4">
    </video>
</div>
<div class="video-text">
    <p class="large-text">Shop System™</p>
    <hr class="long-line">
    <p class="small-text">世界初の金属バインダージェッティングシステムは<br>金属3Dプリンティングを機械工場に導入するために設計されています。<br>標準のターンキーシステムに加えて、Desktop Metalは柔軟性、機能性、価値を高めるために<br>Shop System™+およびShop System™ Proパッケージも提供しています。<br>木材用のShop System Forust Editionも利用可能です。</p>
</div>

{% endblock %}

app/templates/news/detail.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

<div class="container">
    <h1 class="pt-5 mt-4">{{ news.title }}</h1>
    <div class="row">
        <div class="col-md-6">
            <img src="{{ news.image.url }}" alt="{{ news.title }}" class="img-fluid mb-3">
            <p>{{ news.body }}</p>
        </div>
        <div class="col-md-6 mt-5">
            {% if news.item1 %}
                <h3>{{ news.item1 }}</h3>
                <p>{{ news.content1 }}</p>
                <h3>{{ news.item2 }}</h3>
                <p>{{ news.content2 }}</p>
                <h3>{{ news.item3 }}</h3>
                <p>{{ news.content3 }}</p>
            {% endif %}
            <a href="/news" class="btn btn-primary mt-3">Back to System Overview</a>
        </div>
    </div>
</div>

{% endblock %}

app/templates/news/list.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

<div class="container mt-5">
    <h1 class="text-center py-4 mb-1">System Overview</h1>
    <div class="row">
        <div class="col-md-6">
            <img src="{% static 'assets/img/System.jpg' %}" alt="System Overview" class="overview-image">
        </div>
        <div class="col-md-6 mt-5 overview-content">
            <h4>高い生産性</h4>
            <p>金属粉末にレーザーを照射する方式と比べ最大10倍の生産性。 1日部品100～1,000個の生産能力を持ちます。</p>
            <h4>選べる拡張性</h4>
            <p>造形エリアのサイズは4パターン。 最小限の投資で使い始めて、後々拡張することも可能です。</p>
            <h4>優れた造形品質</h4>
            <p>1600dpiの高精細バインダージェットプリントによる優れた造形品質。</p>
            <h4>必要な設備が一式揃う</h4>
            <p>3Dプリンターから焼結炉(ファーネス)まで、金属3Dプリントに必要な設備を一式ご提供。 安心してご導入いただけます。</p>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        {% for news in news_list %}
            <div class="col-md-3 col-sm-6 mb-4 news-item">
                <a href="{% url 'homepage:news_detail' news.pk %}">
                    {% if news.image %}
                        <img src="{{ news.image.url }}" alt="{{ news.title }}" class="img-fluid">
                    {% endif %}
                    <h3>{{ news.title }}</h3>
                </a>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}